Support both shasum and sha1sum utils.

diff --git a/packaging/jenkins/release/fetch_source_deb b/packaging/jenkins/release/fetch_source_deb
--- a/packaging/jenkins/release/fetch_source_deb
+++ b/packaging/jenkins/release/fetch_source_deb
@@ -15,7 +15,16 @@ releaseurl="http://www.maths.uq.edu.au/~bab/beta/$src"
 
 curl --location --output "$debsrc" "$releaseurl"
 
-mysum=`shasum "$debsrc" | cut -f1 -d' '`
+if [ -e /usr/bin/shasum ]; then
+  shasumutil=/usr/bin/shasum
+elif [ -e /usr/bin/sha1sum ]; then
+  shasumutil=/usr/bin/sha1sum
+else
+  echo "ERROR: shasum/sha1sum unavailable"
+  exit 1
+fi
+
+mysum=`"$shasumutil" "$debsrc" | cut -f1 -d' '`
 if [ "$mysum" = "$shasum" ]; then
   echo "Downloaded $debsrc, shasums match"
 else
diff --git a/packaging/jenkins/release/fetch_source_rpm b/packaging/jenkins/release/fetch_source_rpm
--- a/packaging/jenkins/release/fetch_source_rpm
+++ b/packaging/jenkins/release/fetch_source_rpm
@@ -14,7 +14,16 @@ releaseurl="http://www.maths.uq.edu.au/~bab/beta/$src"
 
 curl --location --output "$src" "$releaseurl"
 
-mysum=`shasum "$src" | cut -f1 -d' '`
+if [ -e /usr/bin/shasum ]; then
+  shasumutil=/usr/bin/shasum
+elif [ -e /usr/bin/sha1sum ]; then
+  shasumutil=/usr/bin/sha1sum
+else
+  echo "ERROR: shasum/sha1sum unavailable"
+  exit 1
+fi
+
+mysum=`"$shasumutil" "$src" | cut -f1 -d' '`
 if [ "$mysum" = "$shasum" ]; then
   echo "Downloaded $src, shasums match"
 else
