Fedora version checks.

diff --git a/packaging/docker/user/regina-gen-fedora b/packaging/docker/user/regina-gen-fedora
--- a/packaging/docker/user/regina-gen-fedora
+++ b/packaging/docker/user/regina-gen-fedora
@@ -6,11 +6,19 @@ set -e
 
 release="$1"
 
-echo "Setting up repository for Fedora $release"
+if [ "$release" -lt 24 ]; then
+  echo 'ERROR: For Fedora 24 and earlier, Regina used ad-hoc package downloads.'
+  echo '       RPM repositories were not created.'
+  exit 1
+elif [ "$release" = 30 ]; then
+  echo 'ERROR: Regina was not build for Fedora 30.'
+  exit 1
+fi
 
+echo "Importing Regina's signing key..."
 rpmkeys --import /etc/yum.repos.d/regina-key.asc
 
-# TODO: Check fedora versions
+echo "Setting up repository for Fedora $release"
 
 src=/etc/yum.repos.d/regina.repo
   cat > "$src" <<__END__
