Consolidate fedora/opensuse scripts.

diff --git a/packaging/docker/bab/fedora b/packaging/docker/bab/fedora
--- a/packaging/docker/bab/fedora
+++ b/packaging/docker/bab/fedora
@@ -1,9 +1,14 @@
 #!/usr/bin/env bash
 set -e
 
-# TODO: Change these
-tag=bab/fedora:36
-distribution=fedora-36
+ver="$1"
+case "$ver" in
+  [0-9][0-9]) ;;
+  *) echo "Invalid Fedora version: $ver"; exit 1;;
+esac
+
+tag=bab/fedora:$ver
+distribution=fedora-$ver
 
 myarch="`uname -m`"
 case "$myarch" in
@@ -11,6 +16,9 @@ case "$myarch" in
   aarch64) arch=arm64;;
   *) echo "Unknown architecture: $myarch"; exit 1;;
 esac
+
+echo "Preparing Fedora $ver ($arch)..."
+exit 0
 
 dir="$(mktemp -d ${TMPDIR:-/var/tmp}/docker-mkimage.XXXXXXXXXX)"
 rootfsDir="$dir/rootfs"
@@ -47,9 +55,10 @@ echo '----- Removing /dev and /proc -----'
 rm -rf "$rootfsDir/dev" "$rootfsDir/proc"
 mkdir -p "$rootfsDir/dev" "$rootfsDir/proc"
 
-echo '----- Initialising authselect -----'
-
-chroot "$rootfsDir" authselect select minimal --force
+if [ "$ver" -ge 36 ]; then
+  echo '----- Initialising authselect -----'
+  chroot "$rootfsDir" authselect select minimal --force
+fi
 
 echo '----- Creating Dockerfile -----'
 
diff --git a/packaging/docker/bab/opensuse b/packaging/docker/bab/opensuse
--- a/packaging/docker/bab/opensuse
+++ b/packaging/docker/bab/opensuse
@@ -1,9 +1,14 @@
 #!/usr/bin/env bash
 set -e
 
-# TODO: Change these
-tag=bab/fedora:35
-distribution=fedora-35
+ver="$1"
+case "$ver" in
+  15.[0-9]) ;;
+  *) echo "Invalid openSUSE Leap version: $ver"; exit 1;;
+esac
+
+tag=bab/opensuse:$ver
+distribution=opensuse-$ver
 
 myarch="`uname -m`"
 case "$myarch" in
@@ -11,6 +16,9 @@ case "$myarch" in
   aarch64) arch=arm64;;
   *) echo "Unknown architecture: $myarch"; exit 1;;
 esac
+
+echo "Preparing openSUSE Leap $ver ($arch)..."
+exit 0
 
 dir="$(mktemp -d ${TMPDIR:-/var/tmp}/docker-mkimage.XXXXXXXXXX)"
 rootfsDir="$dir/rootfs"
@@ -21,25 +29,11 @@ echo '----- Bootstrapping distribution -----'
 mkdir -p "$rootfsDir"
 rinse --directory "$rootfsDir" --arch "$arch" --distribution "$distribution"
 
-if [ -d "$rootfsDir/etc/sysconfig" ]; then
-	# allow networking init scripts inside the container to work without extra steps
-	echo 'NETWORKING=yes' > "$rootfsDir/etc/sysconfig/network"
-fi
-
-echo '----- Creating /etc/resolv.conf -----'
-
-# make sure /etc/resolv.conf has something useful in it
-mkdir -p "$rootfsDir/etc"
-rm -f "$rootfsDir/etc/resolv.conf"
-cat > "$rootfsDir/etc/resolv.conf" <<'EOF'
-nameserver 8.8.8.8
-nameserver 8.8.4.4
-EOF
-
 echo '----- Updating distribution -----'
 
-chroot "$rootfsDir" dnf upgrade -y -b --refresh --setopt=install_weak_deps=False
-chroot "$rootfsDir" dnf clean all
+chroot "$rootfsDir" zypper refresh
+chroot "$rootfsDir" zypper update -y
+chroot "$rootfsDir" zypper clean
 
 echo '----- Removing /dev and /proc -----'
 
